#pragma once

#define TRAINER_NONE 0

// Gym Leader
#define TRAINER_GYMLEADER_BROCK 0x19E
#define TRAINER_GYMLEADER_MISTY 0x19F
#define TRAINER_GYMLEADER_SURGE 0x1A0
#define TRAINER_GYMLEADER_ERIKA 0x1A1
#define TRAINER_GYMLEADER_SABRINA 0x1A4
#define TRAINER_GYMLEADER_KOGA 0x1A2
#define TRAINER_GYMLEADER_BLAINE 0x1A3
#define TRAINER_GYMLEADER_GIOVANNI 0x15E

// Elite Four
#define TRAINER_ELITEFOUR_LORELAI_1 0x19A
#define TRAINER_ELITEFOUR_BRUNO_1 0x19B
#define TRAINER_ELITEFOUR_AGATHA_1 0x19C
#define TRAINER_ELITEFOUR_LANCE_1 0x19D

#define TRAINER_ELITEFOUR_LORELAI_2 0x2DF
#define TRAINER_ELITEFOUR_BRUNO_2 0x2E0
#define TRAINER_ELITEFOUR_AGATHA_2 0x2E1
#define TRAINER_ELITEFOUR_LANCE_2 0x2E2

// Rival
#define TRAINER_RIVAL_ROUTE22_SQUIRTLE 0x149
#define TRAINER_RIVAL_ROUTE22_BULBASAUR 0x14A
#define TRAINER_RIVAL_ROUTE22_CHARMANDER 0x14B

// Other Trainers