#include "../../config.h"
#include "../../../include/constants/species.h"
#include "../../../include/constants/items.h"
#include "../../../include/constants/moves.h"
#include "../../../include/constants/event_objects.h"
#include "../../../include/constants/trainer_classes.h"
#include "../../../include/new/catching.h"
#include "../../../include/new/build_pokemon.h"
#include "../../../include/battle.h"
#include "trainerids.h"

extern const u8 sTrainerName_Madeline[];

// Traynee HP Team
static const struct BattleTowerSpread sDifficult_TrayneeHP[] = 
{
    {
		.species = SPECIES_WIGGLYTUFF,
		.nature = NATURE_RELAXED,
		.ability = FRONTIER_ABILITY_2,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_WIGGLYTUFF,
		.nature = NATURE_RELAXED,
		.ability = FRONTIER_ABILITY_2,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_WIGGLYTUFF,
		.nature = NATURE_RELAXED,
		.ability = FRONTIER_ABILITY_2,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_WIGGLYTUFF,
		.nature = NATURE_RELAXED,
		.ability = FRONTIER_ABILITY_2,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_WIGGLYTUFF,
		.nature = NATURE_RELAXED,
		.ability = FRONTIER_ABILITY_2,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_WIGGLYTUFF,
		.nature = NATURE_RELAXED,
		.ability = FRONTIER_ABILITY_2,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},

};
// Traynee Attack
static const struct BattleTowerSpread sDifficult_TrayneeAtt[] = 
{
    {
		.species = SPECIES_VICTREEBEL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_VICTREEBEL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_VICTREEBEL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_VICTREEBEL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_VICTREEBEL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_VICTREEBEL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},

};

// Traynee Defense
static const struct BattleTowerSpread sDifficult_TrayneeDef[] = 
{
    {
		.species = SPECIES_COALOSSAL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_COALOSSAL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_COALOSSAL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_COALOSSAL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_COALOSSAL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_COALOSSAL,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
};

// Traynee Sp Attack
static const struct BattleTowerSpread sDifficult_TrayneeSpA[] = 
{
    {
		.species = SPECIES_BEAUTIFLY,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_BEAUTIFLY,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_BEAUTIFLY,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_BEAUTIFLY,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_BEAUTIFLY,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_BEAUTIFLY,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
};

// Traynee Sp Defense
static const struct BattleTowerSpread sDifficult_TrayneeSpD[] = 
{
    {
		.species = SPECIES_DUSTOX,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_DUSTOX,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_DUSTOX,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_DUSTOX,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_DUSTOX,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_DUSTOX,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
};

// Traynee Speed
static const struct BattleTowerSpread sDifficult_TrayneeSpe[] = 
{
    {
		.species = SPECIES_JUMPLUFF,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_JUMPLUFF,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_JUMPLUFF,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_JUMPLUFF,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_JUMPLUFF,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
    {
		.species = SPECIES_JUMPLUFF,
		.nature = NATURE_RELAXED,
		.level = 5,
		.hpIv = 0,
		.atkIv = 0,
		.defIv = 0,
		.spAtkIv = 0,
		.spDefIv = 0,
		.spdIv = 0,
		.moves ={MOVE_HEALINGWISH},
	},
};

static const struct BattleTowerSpread sDifficult_Proton_MtMoon[] = 
{
    {
		.species = SPECIES_TENTACRUEL,
		.nature = NATURE_TIMID,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.atkEv = 0,
		.defEv = 252,
		.spdEv = 0,
		.spAtkEv = 0,
		.spDefEv = 4,
		.item = ITEM_BLACK_SLUDGE,
		.moves ={MOVE_SCALD, MOVE_HAZE, MOVE_TOXICSPIKES, MOVE_KNOCKOFF},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_1, // clearbody
	},
    {
		.species = SPECIES_MISMAGIUS,
		.nature = NATURE_TIMID,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 0,
		.atkEv = 0,
		.defEv = 0,
		.spdEv = 0,
		.spAtkEv = 252,
		.spDefEv = 4,
		.item = ITEM_LIFE_ORB,
		.moves ={MOVE_SHADOWBALL, MOVE_MOONBLAST, MOVE_POWERGEM, MOVE_NASTYPLOT},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_1, // levitate
	},
    {
		.species = SPECIES_OBSTAGOON,
		.nature = NATURE_JOLLY,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 0,
		.atkEv = 252,
		.defEv = 0,
		.spdEv = 252,
		.spAtkEv = 0,
		.spDefEv = 4,
		.item = ITEM_FLAME_ORB,
		.moves ={MOVE_KNOCKOFF, MOVE_FACADE, MOVE_ICEPUNCH, MOVE_PARTINGSHOT},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_2, // guts
	},
    {
		.species = SPECIES_RILLABOOM,
		.nature = NATURE_ADAMANT,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 0,
		.atkEv = 252,
		.defEv = 0,
		.spdEv = 252,
		.spAtkEv = 0,
		.spDefEv = 4,
		.item = ITEM_CHOICE_BAND,
		.moves ={MOVE_GRASSYGLIDE, MOVE_KNOCKOFF, MOVE_UTURN, MOVE_DRAINPUNCH},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_HIDDEN, // grassy surge
	},
    {
		.species = SPECIES_SCIZOR,
		.nature = NATURE_JOLLY,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.atkEv = 0,
		.defEv = 0,
		.spdEv = 4,
		.spAtkEv = 0,
		.spDefEv = 252,
		.item = ITEM_LIFE_ORB,
		.moves ={MOVE_SWORDSDANCE, MOVE_BULLETPUNCH, MOVE_ROOST, MOVE_KNOCKOFF},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_2, // technician
	},
    {
		.species = SPECIES_TYRANITAR,
		.nature = NATURE_ADAMANT,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 0,
		.spAtkEv = 0,
		.spDefEv = 4,
		.item = ITEM_TYRANITARITE,
		.moves ={MOVE_DRAGONDANCE, MOVE_ICEPUNCH, MOVE_PURSUIT, MOVE_FIREPUNCH},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_1, // sand stream
	},
};

static const struct BattleTowerSpread sDifficult_Ariana_SilphCo[] = 
{
    {
		.species = SPECIES_CORVIKNIGHT,
		.nature = NATURE_CAREFUL,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 248,
		.atkEv = 0,
		.defEv = 8,
		.spdEv = 0,
		.spAtkEv = 0,
		.spDefEv = 252,
		.item = ITEM_LEFTOVERS,
		.moves ={MOVE_BRAVEBIRD, MOVE_UTURN, MOVE_ROOST, MOVE_TAILWIND},
		.shiny = 1,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_1, // pressure
	},
    {
		.species = SPECIES_GARCHOMP,
		.nature = NATURE_JOLLY,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 30,
		.defIv = 30,
		.spAtkIv = 30,
		.spDefIv = 31,
		.spdIv = 30,
		.hpEv = 0,
		.atkEv = 252,
		.defEv = 8,
		.spdEv = 252,
		.spAtkEv = 0,
		.spDefEv = 4,
		.item = ITEM_CHOICE_SCARF,
		.moves ={MOVE_EARTHQUAKE, MOVE_HIDDENPOWER, MOVE_STONEEDGE, MOVE_DRAGONCLAW},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_HIDDEN, // rough skin
	},
    {
		.species = SPECIES_CONKELDURR,
		.nature = NATURE_ADAMANT,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 0,
		.atkEv = 252,
		.defEv = 8,
		.spdEv = 252,
		.spAtkEv = 0,
		.spDefEv = 4,
		.item = ITEM_LIFE_ORB,
		.moves ={MOVE_CLOSECOMBAT, MOVE_MACHPUNCH, MOVE_ICEPUNCH, MOVE_THUNDERPUNCH},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_2, // sheer force
	},
    {
		.species = SPECIES_PORYGON_Z,
		.nature = NATURE_TIMID,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 30,
		.defIv = 31,
		.spAtkIv = 30,
		.spDefIv = 31,
		.spdIv = 30,
		.hpEv = 0,
		.atkEv = 0,
		.defEv = 8,
		.spdEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.item = ITEM_CHOICE_SCARF,
		.moves ={MOVE_THUNDERBOLT, MOVE_DARKPULSE, MOVE_ICEBEAM, MOVE_HIDDENPOWER},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_1, // adaptability
	},
    {
		.species = SPECIES_GLISCOR,
		.nature = NATURE_JOLLY,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 0,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdIv = 31,
		.hpEv = 252,
		.atkEv = 0,
		.defEv = 4,
		.spdEv = 0,
		.spAtkEv = 0,
		.spDefEv = 252,
		.item = ITEM_TOXIC_ORB,
		.moves ={MOVE_EARTHQUAKE, MOVE_ROOST, MOVE_FACADE, MOVE_SWORDSDANCE},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_HIDDEN, // poison heal
	},
    {
		.species = SPECIES_GENGAR,
		.nature = NATURE_TIMID,
		.ball = BALL_TYPE_POKE_BALL,
		.level = 1,
		.hpIv = 30,
		.atkIv = 30,
		.defIv = 31,
		.spAtkIv = 30,
		.spDefIv = 30,
		.spdIv = 30,
		.hpEv = 0,
		.atkEv = 0,
		.defEv = 0,
		.spdEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.item = ITEM_GENGARITE,
		.moves ={MOVE_SHADOWBALL, MOVE_SUBSTITUTE, MOVE_NASTYPLOT, MOVE_HIDDENPOWER},
		.shiny = 0,
		.forSingles = TRUE,
		.forDoubles = TRUE,
		.ability = FRONTIER_ABILITY_1, // levitate
	},
};

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
//@@ Set Trainers
//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
const struct MultiRaidTrainer gImportantTrainers[] = 
{
    {
		.owNum = EVENT_OBJ_GFX_AROMA_LADY,
		.trainerClass = CLASS_AROMA_LADY,
		.backSpriteId = SINGLE_BATTLE,
		.gender = FEMALE,
		.otId = 0x04,
		.name = sTrainerName_Madeline,
		.spreads =
		{
			[0] =	 sDifficult_TrayneeHP,
		},
		.spreadSizes =
		{
			[0] =   NELEMS(sDifficult_TrayneeHP),
		},
    },
    {
		.owNum = EVENT_OBJ_GFX_AROMA_LADY,
		.trainerClass = CLASS_AROMA_LADY,
		.backSpriteId = SINGLE_BATTLE,
		.gender = FEMALE,
		.otId = 0x04,
		.name = sTrainerName_Madeline,
		.spreads =
		{
			[0] =	 sDifficult_TrayneeAtt,
		},
		.spreadSizes =
		{
			[0] =   NELEMS(sDifficult_TrayneeAtt),
		},
    },
    {
		.owNum = EVENT_OBJ_GFX_AROMA_LADY,
		.trainerClass = CLASS_AROMA_LADY,
		.backSpriteId = SINGLE_BATTLE,
		.gender = FEMALE,
		.otId = 0x04,
		.name = sTrainerName_Madeline,
		.spreads =
		{
			[0] =	 sDifficult_TrayneeDef,
		},
		.spreadSizes =
		{
			[0] =   NELEMS(sDifficult_TrayneeDef),
		},
    },
    {
		.owNum = EVENT_OBJ_GFX_AROMA_LADY,
		.trainerClass = CLASS_AROMA_LADY,
		.backSpriteId = SINGLE_BATTLE,
		.gender = FEMALE,
		.otId = 0x04,
		.name = sTrainerName_Madeline,
		.spreads =
		{
			[0] =	 sDifficult_TrayneeSpA,
		},
		.spreadSizes =
		{
			[0] =   NELEMS(sDifficult_TrayneeSpA),
		},
    },
    {
		.owNum = EVENT_OBJ_GFX_AROMA_LADY,
		.trainerClass = CLASS_AROMA_LADY,
		.backSpriteId = SINGLE_BATTLE,
		.gender = FEMALE,
		.otId = 0x04,
		.name = sTrainerName_Madeline,
		.spreads =
		{
			[0] =	 sDifficult_TrayneeSpD,
		},
		.spreadSizes =
		{
			[0] =   NELEMS(sDifficult_TrayneeSpD),
		},
    },
    {
		.owNum = EVENT_OBJ_GFX_AROMA_LADY,
		.trainerClass = CLASS_AROMA_LADY,
		.backSpriteId = SINGLE_BATTLE,
		.gender = FEMALE,
		.otId = 0x04,
		.name = sTrainerName_Madeline,
		.spreads =
		{
			[0] =	 sDifficult_TrayneeSpe,
		},
		.spreadSizes =
		{
			[0] =   NELEMS(sDifficult_TrayneeSpe),
		},
    },
    {
		.owNum = EVENT_OBJ_GFX_GIOVANNI,
		.trainerClass = CLASS_BOSS,
		.backSpriteId = SINGLE_BATTLE,
		.gender = MALE,
		.otId = 6,
		.name = sTrainerName_Madeline,
		.spreads =
		{
			[0] =	 sDifficult_Proton_MtMoon,
		},
		.spreadSizes =
		{
			[0] =   NELEMS(sDifficult_Proton_MtMoon),
		},
    },
    {
		.owNum = EVENT_OBJ_GFX_GIOVANNI,
		.trainerClass = CLASS_BOSS,
		.backSpriteId = SINGLE_BATTLE,
		.gender = MALE,
		.otId = 8,
		.name = sTrainerName_Madeline,
		.spreads =
		{
			[0] =	 sDifficult_Ariana_SilphCo,
		},
		.spreadSizes =
		{
			[0] =   NELEMS(sDifficult_Ariana_SilphCo),
		},
    }
};

const u8 gNumImportantTrainers = NELEMS(gImportantTrainers);